### ISSUE TITLE
Various BlockState Issues Involving Immersive Engineering For foamfix-0.5.0-BETA-anarchy

### ISSUE THREAD

**Issue by DoctorWiggles** [asiekierka/FoamFix#14]
## Metadata blocks seem to be goofing up.

Itemblocks for them carry the same local names and place the same blocks as their defualts

Wooden post for example, which is a member of the water wheel family
![2016-12-31_09 56 21](https://cloud.githubusercontent.com/assets/10700823/21578794/8757370e-cf42-11e6-88b1-38fb17f60302.png)
Places a water wheel instead of the wooden post
![2016-12-31_09 56 33](https://cloud.githubusercontent.com/assets/10700823/21578796/8b1f237e-cf42-11e6-836d-dfd2a4cadc38.png)

Some of them will even crash the game like with the balloon block.
http://paste.ee/p/ImKqZ

For versions:
__ImmersiveEngineering-0.10-54__
__foamfix-0.5.0-BETA-anarchy__

**Comment by asiekierka** [comment]
>UCHIJAAAA	immersiveengineering{0.10-50} [Immersive Engineering] (ImmersiveEngineering-0.10-50.jar) 

Your log clearly says 0.10-50, not 0.10-54. The crash at least was fixed in 0.10-51; could you check the other bug as well?

**Comment by DoctorWiggles** [comment]
Ah, don't know how I quite mixed up my logs there. But yeah you're right it doesn't crash in 0.10-54.
The rest of the goofing still happens however.

**Comment by asiekierka** [comment]
Confirmed. No idea why this is happening yet, but I will get to it.

(Also, the latest GitHub release shaves off another 75MB from RR4. Insane.)
